
version: "3.8"
services:
  reverseproxy:
    container_name: nginx_container
    build:
      context: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    restart: always

  backend:
    container_name: backend_container
    build:
      context: ./api
    #ports:
    #  - "8080:5000"
    volumes:
    - ./:/var/www
    #command: python app.py runserver 0.0.0.0:5000
    networks:
      my-network:
        aliases:
          - backend-app
    restart: always

  frontend:
      container_name: frontend_container
      build:
        context: ./sys-stats
      networks:
        my-network:
          aliases:
            - frontend-app¿
      ports:
        - "4200:4200"
      volumes:
        - ./sys-stats:/sys-stats
      command: ng serve --host 0.0.0.0 --disable-host-check --port 4200 --poll=2000
      restart: always

networks:
  my-network: